import React from 'react'
import webpic from '../images/webpic.png'
import {SubHeadingItem, SubHeadingList, Image, ParagraphItem} from '../Components'
function importAll(r) {
    return r.keys().map(r);
  }
  
  const images = importAll(require.context('../OS_Images', false, /\.(png|jpe?g|svg)$/));
export default function Chapter_1(){
    return(
        <div className="show" id="OS-Chapter-1">
            <SubHeadingList title="Chapter 1 - Introduction">
                <SubHeadingItem content='A computer system can be divided roughly into four components: '> 
                    <ParagraphItem highlight ='blue' content='Hardware'> </ParagraphItem>
                    <ParagraphItem highlight ='blue' content='OS'> </ParagraphItem>
                    <ParagraphItem highlight ='blue' content='application Programs'> </ParagraphItem>
                    <ParagraphItem highlight ='blue' content='user'> </ParagraphItem>

                </SubHeadingItem>

                <SubHeadingItem content='An operating system is software that manages the computer hardware, as well as providing an
                environment for application programs to run'></SubHeadingItem>

                <SubHeadingItem content='Interrupts == key way for hardware to interact with the OS. Interrupt managed by the interrupt handler.'></SubHeadingItem>
                <SubHeadingItem content='Programs must be in memory for a computer to exexcute programs. (L1 and L2 Cache are extensions of Main Memory)'></SubHeadingItem>
            </SubHeadingList>
                <p className='text-center'><Image picture={images[0]}></Image></p>

            <SubHeadingList title='The Role of Interrupts'>
                <SubHeadingItem content='Hardware interaction with the OS.'></SubHeadingItem>
                <SubHeadingItem content='To send signals to the CPU (normally from I/O devices USB, Keyboard, Mouse, etc.)'></SubHeadingItem>
                <SubHeadingItem content='Basically tells the CPU, "Hey I want you to stop what you are doing right now and do this first then continue what you were doing earlier."'></SubHeadingItem>
                <SubHeadingList title='A more sophisticated interrupt handling process:'>
                    <SubHeadingItem content='We need the ability to defer interrupt handling during critical processing.'></SubHeadingItem>
                    <SubHeadingItem content='We need an efficient way to dispatch to the proper interrupt handler for a device.'></SubHeadingItem>
                    <SubHeadingItem content='We need multilevel interrupts, so the OS can distinguish high vs low priority interrupts. This lets the OS respond based on the urgency needed of the given interrupts.'></SubHeadingItem>
                </SubHeadingList>

                <SubHeadingList title='Types of Interrupts'>
                    <SubHeadingList title='Hardware Interrupts' highlight='red'>
                        <SubHeadingItem content='Generated by hardware devices. i.e keyboard usage'></SubHeadingItem>
                    </SubHeadingList>

                    <SubHeadingList highlight='blue' title='Software Interrupts (TRAPS)'>
                        <SubHeadingItem content='generated by programs when they request a system call to the OS'></SubHeadingItem>
                        <SubHeadingItem content='Can also be generated caused by an error (1/0 , segfault, etc.)'></SubHeadingItem>
                    </SubHeadingList>

                    
                </SubHeadingList>
            </SubHeadingList>

            <SubHeadingList title='Main Memory'>
                <SubHeadingItem content='volatile storage device -> loses its contents when power is turned off / lost'></SubHeadingItem>
                <SubHeadingItem content='Only large storage area that the processor can access directly'></SubHeadingItem>
            </SubHeadingList>
            <p className='text-center'><Image picture={images[1]}></Image></p>
            
            <SubHeadingList title='Multiprocessor Systems'>
                <SubHeadingItem content='Contains Processor -- Chip that contains the CPUs(1 or more).'></SubHeadingItem>
                <SubHeadingItem content='Contains CPU -- responsible for executing instructions.'></SubHeadingItem>
                <SubHeadingItem content='Contains Core -- computation unit of the CPU.'></SubHeadingItem>
                <SubHeadingItem content='Multicore -- contains multiple cores on the same CPU'></SubHeadingItem>
                <SubHeadingItem content='Multiprocessor -- contains multiple processors'></SubHeadingItem>

                <SubHeadingItem content='Idea behind Multiprocessor systems: With more processors, we expect to get more work done.'></SubHeadingItem>
                <SubHeadingItem content='Most common multiprocessor systems use symmetric multiprocessing'></SubHeadingItem>
                <SubHeadingList title='Symmetric multiprocessing'>
                    <SubHeadingItem content='multiple processors sharing main memory'></SubHeadingItem>
                    <SubHeadingList title='Advantages:'>
                        <SubHeadingItem content='In a symmetric multiprocess system, you get N processors. Let’s say we have N cpus and we are performing tasks then we run N processes because we have N cpus. '></SubHeadingItem>
                        <SubHeadingItem content='We are able to execute more processes as the amount of cpu grows.'></SubHeadingItem>
                    </SubHeadingList>
                    <SubHeadingList title='Disadvantages:'>
                        <SubHeadingItem content='We need to have space in main memory as N gets bigger N cpus will have to share the main memory.'></SubHeadingItem>
                        <SubHeadingItem content='Another problem with this is one cpu can be overloaded while the other is not. So there is an inefficiency w/ one cpu doing more work.'></SubHeadingItem>
                    </SubHeadingList>
                </SubHeadingList>

                <SubHeadingList title='Multicore Systems'>
                    <SubHeadingItem content='multiple cores in one CPU.'></SubHeadingItem>
                    <SubHeadingList title='Advantages:'>
                        <SubHeadingItem content='Multicores are more efficient than multipchips with 1 core  because in core communication is much faster than between chip comms.'></SubHeadingItem>
                        <SubHeadingItem content='Consumes lower energy than multiple chips (ideal for laptops/phones)'></SubHeadingItem>
                    </SubHeadingList>
                    <SubHeadingList title='Disadvantages:'>
                        <SubHeadingItem content='Consumes more electricity'></SubHeadingItem>
                        <SubHeadingItem content='They are difficult to manage as compared to the single-core processor'></SubHeadingItem>
                    </SubHeadingList>
                    <SubHeadingList title='How this affects Programmers?'>
                        <SubHeadingItem content='Main difficulty that a programmer must overcome in writing an operating system for a real time environment is to make efficient use of the processing cores that a multicore system provides.'></SubHeadingItem>
                    </SubHeadingList>
                    <SubHeadingList title='Applications:'>
                        <SubHeadingItem content='Gaming'></SubHeadingItem>
                        <SubHeadingItem content='DB servers'></SubHeadingItem>
                        <SubHeadingItem content='Encoding'></SubHeadingItem>
                        <SubHeadingItem content='Video Editing'></SubHeadingItem>
                        <SubHeadingItem content='etc.'></SubHeadingItem>
                    </SubHeadingList>
                </SubHeadingList>
            </SubHeadingList>

            <SubHeadingList title='Transition from Kernel Mode to User Mode (Multimode/ Dual-Mode Operations)'>
                <SubHeadingList title='How does the computer know which to use?'>
                    <SubHeadingItem content='The mode bit in the hardware tells the computer which mode to use. Mode(0) | User(1)'></SubHeadingItem>
                    <Image picture={images[2]}></Image>
                    
                </SubHeadingList>
                
                <SubHeadingList title='Kernel Mode (0)'>
                    <SubHeadingItem content='Allows us to execute privelege instructions.'></SubHeadingItem>
                    <SubHeadingList title='Privilege instructions examples:'>
                        <SubHeadingItem content='Timer: set to inerrupt the computer after a specified period.'></SubHeadingItem>
                        <Image picture={images[3]}></Image>
                        <SubHeadingItem content='Clearing the memory: can be dangerous if done wrong.'></SubHeadingItem>
                        <SubHeadingItem content='Turning off interrupts'></SubHeadingItem>
                        <SubHeadingItem content='Modify entries in device-status table'></SubHeadingItem>
                        <SubHeadingItem content='Switching from User(1) to Kernel(0) mode: user can accidentally switch w/o knowing so it is privileged.'></SubHeadingItem>
                        <SubHeadingItem content='Accessing I/O devices'></SubHeadingItem>




                    </SubHeadingList>
                </SubHeadingList>
            </SubHeadingList>

            <SubHeadingList title='Multiprogramming'>
                <SubHeadingItem content='Run multiple programs simultaneously.'></SubHeadingItem>
                <SubHeadingItem content='CPU constantly has a job.'></SubHeadingItem>
                <SubHeadingItem content='OS can have N amount of jobs. An extension of multiprogramming called Multitasking responsible for applying CPU scheduling algorithms that rapidly switch between processes, providing users with a fast response time.'></SubHeadingItem>
                <SubHeadingList title='Goal: An increase in CPU utilization '>
                    <SubHeadingItem content='Program could be waiting for an input'></SubHeadingItem>
                    <SubHeadingItem content='Program could be waiting for device access.'></SubHeadingItem>
                    <SubHeadingItem content='Multiple jobs could be running and the OS alternates in running these jobs.'></SubHeadingItem>
                </SubHeadingList>
                <SubHeadingList title='What could go wrong w/ Multiprogramming? (OS has to manage these issues)'>
                    <SubHeadingList title='Perfomance Issues:'>
                        <SubHeadingItem content='Not enough memory for all jobs.'></SubHeadingItem>
                        <SubHeadingItem content='Jobs taking too much or little share of CPU'></SubHeadingItem>
                        <SubHeadingItem content='Multiple Jobs competing for same resource'></SubHeadingItem>
                    </SubHeadingList>
                    <SubHeadingList title='Security Issues:'>
                        <SubHeadingItem content='Jobs modifying shared memory or file.'></SubHeadingItem>
                    </SubHeadingList>
                    
                </SubHeadingList>
            
            </SubHeadingList>

            <SubHeadingList title='Program vs Process'>
                    <SubHeadingItem content='Program is a passive entity, process is an active entity'></SubHeadingItem>
                    <SubHeadingItem content='Program is a group of instructions to carry out a task it is given.'></SubHeadingItem>
                    <SubHeadingItem content='Process is a program in execution.'></SubHeadingItem>
                    <SubHeadingItem content='Process is the soul. Without a Soul, the body cannot move.'></SubHeadingItem>
            </SubHeadingList>
            
            <SubHeadingList title='Security vs Protection'>
                <SubHeadingItem content='Protection: Managing access among authentic users.'></SubHeadingItem>
                <SubHeadingItem content='Security: Protecting the system from malicious software.'></SubHeadingItem>
            </SubHeadingList>

            <SubHeadingList title='Hardware Components'>
                <SubHeadingItem content='CPU'></SubHeadingItem>
                <SubHeadingItem content='Memory'></SubHeadingItem>
                <SubHeadingItem content='Input'></SubHeadingItem>
                <SubHeadingItem content='Output'></SubHeadingItem>
            </SubHeadingList>

            <SubHeadingList title='Some of the Memory Components'>
                <SubHeadingItem content='Registers (Not really considered)'></SubHeadingItem>
                <SubHeadingItem content='Cache'></SubHeadingItem>
                <SubHeadingItem content='Main Memory'></SubHeadingItem>
                <SubHeadingItem content='Hard Disk'></SubHeadingItem>
                <SubHeadingItem content='etc.'></SubHeadingItem>
            </SubHeadingList>

            <SubHeadingList title='Modern Computer Architecture'>
                <SubHeadingItem content='Instruction Data both stored in unified memory.'></SubHeadingItem>
                <Image picture={images[4]}></Image>
            </SubHeadingList>
            <SubHeadingList title='Instruction Cycle'>
                <SubHeadingItem content='Fetch Instruction'></SubHeadingItem>
                <SubHeadingItem content='Decode Instruction'></SubHeadingItem>
                <SubHeadingItem content='Execute Instruction'></SubHeadingItem>
            </SubHeadingList>

            
        </div>
    )
}